# Generated by Django 6.0 on 2026-06-01 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('AUTH', 'Auth'), ('TENANT_ADMIN', 'Tenant admin'), ('SYSTEM_ADMIN', 'System admin'), ('MODULE_READ', 'Module read'), ('MODULE_WRITE', 'Module write'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
