# Generated by Django 6.0 on 2026-06-01 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_timesheet_projects_ti_tenant__0cfbd5_idx'),
        ('tasks', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', '-id'], name='tasks_task_tenant__5b60ca_idx'),
        ),
    ]
