# Generated by Django 6.0 on 2026-06-01 13:34
# Hand-edited to inject a pre-flight RunPython sanity check that fails fast
# with a useful error if any existing User row would violate the XOR rule.
# Without this, the bare AddConstraint aborts the migration with an opaque
# IntegrityError on production upgrades.

from django.db import migrations, models


# Inlined to keep the migration self-contained against future model edits.
# Mirrored as USER_XOR_VIOLATOR_Q_V1 in apps.accounts.models for tests.
_VIOLATOR_Q = ~(
    models.Q(is_system_admin=True, tenant__isnull=True)
    | models.Q(is_system_admin=False, tenant__isnull=False)
    | models.Q(is_superuser=True, is_system_admin=False, tenant__isnull=True)
)


def _check_xor_violations(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    bad = list(User.objects.filter(_VIOLATOR_Q).values_list("pk", flat=True)[:51])
    if not bad:
        return
    sample = bad[:50]
    count_label = f"{len(bad)}" if len(bad) <= 50 else "50+"
    suffix = f" ...and at least {len(bad) - 50} more" if len(bad) > 50 else ""
    raise RuntimeError(
        f"accounts.0003 cannot proceed: {count_label} User row(s) violate the "
        f"tenant/system_admin XOR rule. Offending PKs (first 50): "
        f"{sample}{suffix}. Audit and repair these rows before migrating."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_check_xor_violations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system_admin', True), ('tenant__isnull', True)), models.Q(('is_system_admin', False), ('tenant__isnull', False)), models.Q(('is_superuser', True), ('is_system_admin', False), ('tenant__isnull', True)), _connector='OR'), name='user_tenant_xor_system_admin'),
        ),
    ]
