# Generated by Django 6.0 on 2026-06-07 16:42
#
# Adds the user-controllable sort_order field on TenantModule plus a
# data-migration step that initialises existing rows so their menu order
# matches insertion order rather than tying at 0 (which would collapse
# to alphabetical by module name overnight). New rows continue to
# default to 0; the views that create rows are responsible for picking
# a sane fresh value (see apps.sys_admin.views.tenant_module_toggle and
# apps.tenants.signals.on_tenant_created).

from django.db import migrations, models


def _backfill_sort_order(apps, schema_editor):
    TenantModule = apps.get_model("tenants", "TenantModule")
    # For each tenant, assign sort_order = 10, 20, 30, ... in pk order.
    # The 10-step interval gives a tiny bit of headroom for one-off
    # "move between A and B" inserts before the next admin reorder
    # without renumbering, but it's not load-bearing.
    from collections import defaultdict
    by_tenant: dict[int, list[int]] = defaultdict(list)
    for tm_id, tenant_id in TenantModule.objects.order_by("pk").values_list("pk", "tenant_id"):
        by_tenant[tenant_id].append(tm_id)
    for tenant_id, pks in by_tenant.items():
        for index, pk in enumerate(pks):
            TenantModule.objects.filter(pk=pk).update(sort_order=(index + 1) * 10)


def _reverse_backfill(apps, schema_editor):
    # No-op: removing the column reverses cleanly.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantmodule",
            options={"ordering": ("sort_order", "module__name")},
        ),
        migrations.AddField(
            model_name="tenantmodule",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(_backfill_sort_order, _reverse_backfill),
    ]
