# Generated by Django 6.0 on 2026-06-01 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_tickets', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketreply',
            index=models.Index(fields=['tenant', '-id'], name='support_tic_tenant__e17d72_idx'),
        ),
    ]
