# Generated by Django 6.0 on 2026-06-01 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rulerun',
            index=models.Index(fields=['tenant', '-created_at'], name='automation__tenant__988da6_idx'),
        ),
    ]
