# Generated by Django 6.0 on 2026-06-01 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_assets', 'Can view assets'), ('manage_assets', 'Can manage assets')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('depreciation_method', models.CharField(choices=[('STRAIGHT_LINE', 'Straight line'), ('REDUCING_BALANCE', 'Reducing balance')], default='STRAIGHT_LINE', max_length=20)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('IN_USE', 'In use'), ('IN_STORAGE', 'In storage'), ('DISPOSED', 'Disposed'), ('UNDER_REPAIR', 'Under repair')], default='IN_USE', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('asset_no',),
            },
        ),
    ]
